### PR TITLE
Replaced cljx with cljc. 

### PR DESCRIPTION
**Pull request by bensu**
cljs tests are passing but `lein test` runs no tests. Sorry, I thought this was the case in master. I'll update the PR when this issue is resolved.

Hope this helps.

### CODE REVIEW

**Comment by bensu** [comment]
lein doesn't find `.cljc` test files, which should be solved by [#1991](https://github.com/technomancy/leiningen/pull/1911)

**Comment by bensu** [comment]
Running the tests with:

     lein repl
     user> (run-tests)

works alright.

**Comment by jamesmacaulay** [comment]
Thank you, this is very much appreciated!

**Comment by bensu** [comment]
`lein test` now works with the latest leiningen (`2.5.2`)

To get it run `lein upgrade`

**Comment by jamesmacaulay** [comment]
nice :+1:

**Pull request merged**
